### ISSUE TITLE
Location of brew and iproxy binaries not always in `/opt/homebrew`

### ISSUE THREAD

**Issue by PoomSmart** [ginsudev/iLocalConnect#2]
If you install [brew](https://brew.sh) on macOS, normally itself and its packages go to `/usr/local`.

```sh
$ which brew iproxy
/usr/local/bin/brew
/usr/local/bin/iproxy
```

This creates false positives.

<img width="286" alt="image" src="https://user-images.githubusercontent.com/3608783/210135419-e2509d69-71e8-4523-a1ef-2cc6b6e4654b.png">

**Comment by ginsudev** [comment]
Hmm thanks, wasn't aware of that. I'll have it fixed asap 👍
